# database:
#   driver-name: mysql
#   username: root
#   password: line1234
#   host: 127.0.0.1
#   port: 3306
#   db-name: apcs
database:
  driver-name: mysql
  username: apcs_dev
  password: apcs@123
  host: lineworldap.iptime.org
  port: 33306
  dbname: apcs_dev

logging:
  level: debug
  output: terminal  # terminal: 터미널에 color, file: 로그파일에 color

webserver:
  server:
    host: 0.0.0.0
    port: 3000

messenger:
  timeout:
    # 메시지를 허브에 전파할 때 대기하는 시간 제한(초)
    spread: 3
    # 메시지 응답을 기다리는 시간 제한(초)
    response: 3

plc:
  resource:
    robot:
      # 로봇 개수
      number: 2
      robots:
        - id: 1
          home:
            x: 0
            z: 0
        - id: 2
          home:
            x: 10
            z: 0
    # 데드락 상태를 확인하는 주기
    deadlock-check-period: 10
  simulation:
    # 시뮬레이션 속도 배율
    # 0일 경우 딜레이 없이 진행됨
    delay: 1
  trayBuffer:
    # 트레이 버퍼의 최대 개수
    optimum: 20
    init: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] #트레이 버퍼에 있는 초기 빈트레이 / 밑에 있는 트레이부터 등록

sorting:
  # 정리 동작 여부
  state: off # on: 동작, off: 미동작

kiosk:
  #광고 여부
  ad: off #on: 광고 켜기, off: 광고 끄기