database:
  driver-name: mysql
  username: apcs_dev
  password: apcs@123
  host: lineworldap.iptime.org
  port: 33306
  db-name: apcs_dev

logging:
  level: debug

websocket:
  server:
    host: localhost
    port: 3000

messenger:
  timeout:
    # 메시지를 허브에 전파할 때 대기하는 시간 제한(초)
    spread: 3
    # 메시지 응답을 기다리는 시간 제한(초)
    response: 3

plc:
  resource:
    robot:
      # 로봇 개수
      number: 2
      job:
        # 로봇 상태를 확인하고 job을 배정 하는 주기(ms)
        polling-period: 100
  simulation:
    # 시뮬레이션 속도 배율
    # 0일 경우 딜레이 없이 진행됨
    delay: 1
